[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "{{ cookiecutter.project_slug}}"
author = "{{ cookiecutter.full_name }}"
author-email = "{{ cookiecutter.email }}"
home-page = 'https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}'
requires-python = "~={{ cookiecutter.python_version }}"
requires = []
classifiers = [
  'Programming Language :: Python :: 3',
  'License :: OSI Approved :: MIT License',
]

[tool.flit.metadata.urls]
'Documentation' = 'https://{{ cookiecutter.project_slug }}.readthedocs.io/en/latest/'
'Version Control' = 'https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}'
'Bug Tracker' = 'https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}/issues'
'Continuous Integration' = 'https://travis-ci.org/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}'
'Test Coverage' = 'https://coveralls.io/github/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}'


